### ISSUE TITLE
Is there support swift 5.0 plan?

### ISSUE THREAD

**Issue by jrjohn** [andrealufino/Luminous#23]
![image](https://user-images.githubusercontent.com/6859844/163914700-98d8f26e-0871-4f69-ad72-61147a95fbc9.png)
Thanks.

**Comment by andrealufino** [comment]
Hello! Yes, I'm working on it 👍🏻

**Comment by andrealufino** [comment]
Hello! The project already supports Swift 5 as you can see in the Build Settings of the Pods project. These deprecation messages are part of the library because I replaced the old multiple methods with a single one. What it needs to be fixed is the first warning. 
I hope I clarified the problem. If you have doubts or if I misunderstood the question, feel free to go on with this discussion.

**Comment by andrealufino** [comment]
Closing due to no updates. Feel free to reopen.
